"""
File: rectifying.py
Author: Kai Richter
Date: 2023-07-31

Last modified on 2023-11-10 by Kai Richter:
  - Added functions for Circle Detection (CD) and Point Filtering (PF)

Last modified on 2024-03-15 by Spaska Forteva:
  - Added error handling and improved robustness

Description:
This script performs geometric rectification of georeferenced GeoTIFF
files generated in the previous processing step ("Georeferencing").

During georeferencing, raster images are transformed based on Ground
Control Points (GCPs), which can introduce geometric distortions such as:
- warped or curved edges
- non-rectangular boundaries
- uneven pixel distribution

The rectification step applies GDAL-based warping to:
- straighten image borders
- correct geometric distortions
- ensure spatial consistency of raster data

Core Function:
- rectifying():
  Applies GDAL Warp to resample and correct raster geometry.
  Distorted edges are effectively filled with background values (0),
  resulting in clean, rectangular raster outputs.

Workflow Variants:
- mainRectifying():
  Processes rectification for masked symbol images.

- mainRectifying_CD():
  Processes rectification for centroid masks generated by
  Circle Detection.

- mainRectifying_PF():
  Processes rectification for centroid masks generated by
  Point Filtering, supporting multiple map types.

Role in Pipeline:
This step ensures that all raster outputs are geometrically stable
and spatially consistent before further processing steps such as
polygonization and spatial analysis.
"""

#### Script for iteratively rectifying the georeferenced output GeoTIFF files from '5. Georeferencing'.

import sys

import rasterio
from osgeo import gdal, osr
import os, glob


# ------------------------------------------------------------
# Core rectification function
# ------------------------------------------------------------
# Purpose:
# This function performs geometric rectification of already
# georeferenced raster images using GDAL.
#
# Background:
# After georeferencing (based on GCPs), raster images may still
# contain distortions such as:
# - curved or warped edges
# - non-rectangular boundaries
# - irregular pixel alignment
#
# These artefacts are typical results of transformation models
# applied during georeferencing.
#
# Method:
# - The input raster is opened using GDAL
# - gdal.Warp() is applied to reproject and resample the image
# - The result is written as a new GeoTIFF with corrected geometry
#
# Result:
# - Straightened image borders
# - Improved geometric consistency
# - Cleaner input for downstream processing (e.g., polygonization)
#
# Notes:
# - This step does NOT change content, only geometry
# - It ensures that raster data aligns properly with spatial coordinates
# ------------------------------------------------------------
def rectifying(input_raster, output_raster):
    # Öffnen des Quell-Datasets
    src_ds = gdal.Open(input_raster)
    if src_ds is None:
        print(f"Fehler beim Öffnen der Eingabedatei: {input_raster}")
        return
    
    # Bestimmen des Ausgabepfads
    output_raster, file_extension = os.path.splitext(output_raster)
    dst_path = output_raster + ".tif"
    
    # Überprüfen, ob das Zielverzeichnis vorhanden ist, andernfalls erstellen
    output_dir = os.path.dirname(dst_path)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    try:
        # Ausführen der Rektifizierung mit gdal.Warp()
        dst_ds = gdal.Warp(dst_path, src_ds)
        dst_ds = None
        src_ds = None
        print(f"Rektifizierte Datei gespeichert: {dst_path}")
    except Exception as e:
        print(f"Fehler bei der Rektifizierung: {e}")

#input_raster = "D:/test/output_2024-07-12_08-18-21/georeferencing/maps/pointFiltering"

# ------------------------------------------------------------
# Main workflow for rectifying maps (Point Filtering version)
# ------------------------------------------------------------
# Purpose:
# Applies rectification to all georeferenced map images that were
# generated from Point Filtering results.
#
# Input:
# - Georeferenced raster maps containing detected centroids
#
# Output:
# - Rectified raster maps with corrected geometry
#
# Processing steps:
# 1. Locate input directory:
#    georeferencing/maps/pointFiltering/
# 2. Iterate over all TIFF files
# 3. Apply rectification to each file
# 4. Save results in:
#    rectifying/maps/
#
# Importance:
# - Ensures maps are geometrically stable before spatial analysis
# - Removes distortions introduced during georeferencing
#
# Design decision:
# - Batch processing per directory for efficiency
# - File names are preserved for traceability
# ------------------------------------------------------------
def mainRectifying_Map_PF(workingDir, outDir):
    try:
        output = os.path.join(outDir, "rectifying", "maps")
        os.makedirs(output, exist_ok=True) 
        inputdir = os.path.join(outDir, "georeferencing", "maps", "pointFiltering")
        print("Input Directory:", inputdir)
        
        # Adjusted glob.glob to correctly capture all TIFF files
        for input_raster in glob.glob(inputdir + "/*.tif"):
            print("Input TIFF:", input_raster)
            dst_layername = os.path.basename(input_raster)
            print("Destination Layer Name:", dst_layername)
            output_raster = os.path.join(output, dst_layername)
            print("Output Raster Path:", output_raster)
            # Assuming rectifying() is a function you have defined elsewhere
            rectifying(input_raster, output_raster)
    
    except Exception as e:
        print("An error occurred in mainRectifying_Map_PF:", e)
    # End of function


# ------------------------------------------------------------
# Main workflow for rectifying masked centroid images
# ------------------------------------------------------------
# Purpose:
# Rectifies raster images containing centroid masks after
# georeferencing.
#
# Input:
# - Masked raster images (binary or colored centroid layers)
#
# Output:
# - Rectified mask images with corrected geometry
#
# Key idea:
# Even binary masks can be geometrically distorted after
# georeferencing → rectification is required to:
# - align masks with real-world coordinates
# - ensure correct spatial overlay
#
# Processing:
# - Iterate over all mask TIFF files
# - Apply rectifying() function
# - Save outputs in rectifying/ directory
#
# Notes:
# - Essential for accurate polygon generation
# - Prevents spatial misalignment in later steps
# ------------------------------------------------------------
def mainRectifying(workingDir, outDir):
  try:
    output= outDir + "/rectifying/"
    os.makedirs(output, exist_ok=True) 
    inputdir = outDir +"/georeferencing/masks/"
    print(inputdir)
    for input_raster in glob.glob(inputdir + "*.tif"):
      print(input_raster)
      dst_layername = os.path.basename(input_raster)
      print(dst_layername)
      output_raster = output + dst_layername
      print(output_raster)
      rectifying(input_raster, output_raster)
  except Exception as e:
        print("An error occurred in mainRectifying:", e)
  # End of function


# ------------------------------------------------------------
# Rectifying workflow for Circle Detection results
# ------------------------------------------------------------
# Purpose:
# Applies rectification specifically to centroid masks generated
# by Circle Detection (CD) workflow.
#
# Difference to PF:
# - Input data originates from circle-based detection instead of
#   template-based point matching
#
# Workflow:
# - Input: georeferencing/masks/circleDetection/
# - Output: rectifying/circleDetection/
#
# Motivation:
# - Maintain consistency across different detection strategies
# - Ensure both pipelines (CD and PF) produce geometrically
#   comparable outputs
#
# Result:
# - Standardized spatial geometry for all detection approaches
# ------------------------------------------------------------
def mainRectifying_CD(workingDir, outDir):
  try:
    output= outDir + "/rectifying/circleDetection/"
    os.makedirs(output, exist_ok=True) 
    inputdir = outDir +"/georeferencing/masks/circleDetection/"
    
    for input_raster in glob.glob(inputdir + "*.tif"):
      print(input_raster)
      dst_layername = os.path.basename(input_raster)
      print(dst_layername)
      output_raster = output + dst_layername
      print(output_raster)
      rectifying(input_raster, output_raster)
  except Exception as e:
        print("An error occurred in mainRectifying_CD:", e)
  # End of function



# ------------------------------------------------------------
# Rectifying workflow for Point Filtering (multi map-type version)
# ------------------------------------------------------------
# Purpose:
# Applies rectification to multiple map types (e.g., 1, 2, …),
# each processed independently in the pipeline.
#
# Key concept:
# The Distribution Digitizer supports multiple map groups
# (e.g., different symbol systems or datasets).
#
# Workflow:
# For each map type:
# 1. Locate input directory:
#    <outDir>/<map_type>/georeferencing/masks/pointFiltering/
# 2. Locate output directory:
#    <outDir>/<map_type>/rectifying/pointFiltering/
# 3. Process all TIFF files
# 4. Apply rectification
#
# Robustness:
# - Skips map types without data
# - Provides debug output for traceability
#
# Importance:
# - Ensures consistent geometry across all map types
# - Enables scalable processing of large datasets
#
# Design advantage:
# - Modular structure allows independent processing per map type
# - Facilitates parallelization and debugging
# ------------------------------------------------------------
def mainRectifying_PF(workingDir, outDir, nMapTypes=1):

    print(f"DEBUG Rectifying nMapTypes = {nMapTypes}")

    for i in range(1, nMapTypes + 1):

        print(f"\n=== Rectifying map type {i} ===")

        inputdir = os.path.join(
            outDir, str(i), "georeferencing", "masks", "pointFiltering"
        )

        output = os.path.join(
            outDir, str(i), "rectifying", "pointFiltering"
        )

        os.makedirs(output, exist_ok=True)

        print("Input directory:", inputdir)
        print("Output directory:", output)

        tif_files = glob.glob(os.path.join(inputdir, "*.tif"))

        if not tif_files:
            print("⚠️ No tif files found for rectifying")
            continue

        for input_raster in tif_files:
            print("Rectifying:", input_raster)

            dst_layername = os.path.basename(input_raster)
            output_raster = os.path.join(output, dst_layername)

            rectifying(input_raster, output_raster)

#mainRectifying_PF( "D:/distribution_digitizer/", "D:/test/output_2026-02-20_08-40-28/", 2)
